@echo off
REM ==============================================================================
REM HDF5 Library Build Script for Windows
REM ==============================================================================
REM
REM This script drives the CMake project in this directory, which downloads a
REM pinned HDF5 release, builds the static C/C++ libraries and stages the
REM headers and libraries into the output directory.
REM
REM Requirements:
REM   - CMake 3.26 or higher
REM   - Visual Studio 2019 or higher (with C++ tools)
REM   - Git (the HDF5 source is cloned at configure time)
REM   - Network access on the first configure
REM
REM Output:
REM   - .\output\include\               - Common HDF5 C/C++ headers
REM   - .\output\include_win_x86_64\    - Headers generated by the build
REM   - .\output\lib_win_x86_64\        - Static library files (.lib)
REM
REM Usage:
REM   build.bat [options]
REM
REM Arguments:
REM   clean   - Force clean build (removes all build artifacts)
REM   debug   - Build in Debug mode (default is Release)
REM
REM Examples:
REM   build.bat              - Release build
REM   build.bat debug        - Debug build
REM   build.bat clean        - Clean Release build
REM   build.bat clean debug  - Clean Debug build
REM
REM ==============================================================================

REM Configuration - defaults
set BUILD_TYPE=Release
set BUILD_DIR=.\build
set OUTPUT_DIR=.\output
set FORCE_CLEAN=

REM Parse command line arguments
:parse_args
if "%1"=="" goto done_args
if /i "%1"=="clean" (
    set FORCE_CLEAN=1
    echo INFO: Force clean build requested
)
if /i "%1"=="debug" (
    set BUILD_TYPE=Debug
    echo INFO: Debug build requested
)
shift
goto parse_args
:done_args

echo INFO: Build type: %BUILD_TYPE%

REM Check if CMake is available
cmake --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: CMake is not installed or not in PATH
    echo Please install CMake 3.26 or higher
    exit /b 1
)

REM Check if Git is available - CMake clones the HDF5 source with it
git --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Git is not installed or not in PATH
    exit /b 1
)

REM Clean old build files
echo INFO: Cleaning old build files...
if exist "%BUILD_DIR%" (
    rmdir /q /s "%BUILD_DIR%" 2>nul
    if %errorlevel% neq 0 (
        echo WARNING: Failed to remove build directory, continuing...
    )
)

if exist "%OUTPUT_DIR%" (
    if defined FORCE_CLEAN (
        rmdir /q /s "%OUTPUT_DIR%" 2>nul
        if %errorlevel% neq 0 (
            echo WARNING: Failed to remove output directory, continuing...
        )
    )
)

REM Configure CMake
echo INFO: Configuring CMake...
cmake -S . -B "%BUILD_DIR%" -DCMAKE_BUILD_TYPE:STRING=%BUILD_TYPE%

if %errorlevel% neq 0 (
    echo ERROR: CMake configuration failed
    exit /b 1
)

REM Build the project - this also stages the headers and libraries
echo INFO: Building HDF5 libraries...
cmake --build "%BUILD_DIR%" --config %BUILD_TYPE% --parallel

if %errorlevel% neq 0 (
    echo ERROR: Build failed
    exit /b 1
)

echo INFO: Build completed successfully!
echo INFO: Output: %OUTPUT_DIR%
echo INFO: Build artifacts: %BUILD_DIR%

exit /b 0
