@echo off
setlocal enabledelayedexpansion
REM ==============================================================================
REM Prebuilt Dependency Build Script for Windows
REM ==============================================================================
REM
REM Drives the superbuild in this directory, which downloads pinned releases of
REM every selected dependency, builds them against a shared ABI baseline and
REM stages headers and static libraries into the output directory.
REM
REM Requirements:
REM   - CMake 3.26 or higher
REM   - Visual Studio 2019 or higher (with C++ tools)
REM   - Git (the HDF5 source is cloned at configure time)
REM   - Network access on the first configure
REM
REM Output:
REM   - .\output\<dep>\include\               - Portable headers
REM   - .\output\<dep>\include_win_x86_64\    - Headers generated by the build
REM   - .\output\<dep>\lib_win_x86_64\        - Static library files (.lib)
REM   - .\dist\                               - Release archives (with 'package')
REM
REM Usage:
REM   build.bat [options]
REM
REM Arguments:
REM   clean     - Force clean build (also removes the staged output directory)
REM   debug     - Build in Debug mode (default is Release)
REM   hdf5      - Build only HDF5
REM   mbedtls   - Build only mbedTLS
REM   package   - Also produce release archives and checksums in .\dist
REM
REM Naming a dependency restricts the build to the ones named; with none named,
REM every dependency is built. Arguments may be given in any order.
REM
REM Examples:
REM   build.bat                    - Release build of everything
REM   build.bat mbedtls            - Release build of mbedTLS only
REM   build.bat clean debug        - Clean Debug build of everything
REM   build.bat clean package      - Clean build, then archive for a release
REM
REM ==============================================================================

REM Configuration - defaults
set BUILD_TYPE=Release
set BUILD_DIR=.\build
set OUTPUT_DIR=.\output
set DIST_DIR=.\dist
set FORCE_CLEAN=
set DO_PACKAGE=
set ANY_SELECTED=
set BUILD_HDF5=OFF
set BUILD_MBEDTLS=OFF

REM Parse command line arguments
:parse_args
if "%1"=="" goto done_args
if /i "%1"=="clean" (
    set FORCE_CLEAN=1
    echo INFO: Force clean build requested
) else if /i "%1"=="debug" (
    set BUILD_TYPE=Debug
    echo INFO: Debug build requested
) else if /i "%1"=="package" (
    set DO_PACKAGE=1
    echo INFO: Release packaging requested
) else if /i "%1"=="hdf5" (
    set BUILD_HDF5=ON
    set ANY_SELECTED=1
) else if /i "%1"=="mbedtls" (
    set BUILD_MBEDTLS=ON
    set ANY_SELECTED=1
) else (
    echo ERROR: Unknown argument: %1
    echo Usage: build.bat [clean] [debug] [package] [hdf5] [mbedtls]
    exit /b 1
)
shift
goto parse_args
:done_args

REM No dependency named means build all of them
if not defined ANY_SELECTED (
    set BUILD_HDF5=ON
    set BUILD_MBEDTLS=ON
)

echo INFO: Build type: %BUILD_TYPE%
echo INFO: hdf5=%BUILD_HDF5% mbedtls=%BUILD_MBEDTLS%

REM Check if CMake is available
cmake --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: CMake is not installed or not in PATH
    echo Please install CMake 3.26 or higher
    exit /b 1
)

REM Check if Git is available - CMake clones the HDF5 source with it
git --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Git is not installed or not in PATH
    exit /b 1
)

REM Clean old build files
echo INFO: Cleaning old build files...
if exist "%BUILD_DIR%" (
    rmdir /q /s "%BUILD_DIR%" 2>nul
    if %errorlevel% neq 0 (
        echo WARNING: Failed to remove build directory, continuing...
    )
)

if defined FORCE_CLEAN (
    if exist "%OUTPUT_DIR%" rmdir /q /s "%OUTPUT_DIR%" 2>nul
    if exist "%DIST_DIR%" rmdir /q /s "%DIST_DIR%" 2>nul
)

REM Configure CMake
echo INFO: Configuring CMake...
cmake -S . -B "%BUILD_DIR%" -DCMAKE_BUILD_TYPE:STRING=%BUILD_TYPE% -DDEPS_BUILD_HDF5:BOOL=%BUILD_HDF5% -DDEPS_BUILD_MBEDTLS:BOOL=%BUILD_MBEDTLS%

if %errorlevel% neq 0 (
    echo ERROR: CMake configuration failed
    exit /b 1
)

REM Build the project - this also stages the headers and libraries
echo INFO: Building dependencies...
cmake --build "%BUILD_DIR%" --config %BUILD_TYPE% --parallel

if %errorlevel% neq 0 (
    echo ERROR: Build failed
    exit /b 1
)

REM Package for a GitHub release
if defined DO_PACKAGE (
    echo INFO: Packaging release archives...
    cmake --build "%BUILD_DIR%" --config %BUILD_TYPE% --target package-release
    if %errorlevel% neq 0 (
        echo ERROR: Packaging failed
        exit /b 1
    )
    echo INFO: Archives and checksums in %DIST_DIR%
)

echo INFO: Build completed successfully!
echo INFO: Output: %OUTPUT_DIR%
echo INFO: Build artifacts: %BUILD_DIR%

exit /b 0
