# -----------------------------------------------------------------------------
# platform.cmake - resolve the platform triplet used for staged output
# -----------------------------------------------------------------------------
# Every prebuilt dependency is staged into directories suffixed with the same
# platform name so that a consumer can resolve all of them with one rule:
#
#   libs/<dep>/include/              - portable headers
#   libs/<dep>/include_<platform>/   - headers generated by the build (optional)
#   libs/<dep>/lib_<platform>/       - static libraries
#
# Include this from a CMake project (it needs CMAKE_SYSTEM_NAME) and it will
# define DEPS_PLATFORM in the including scope.
#
# The exact same logic lives in the consumer, in radarsimcpp's
# cmake/PrebuiltDeps.cmake. If you change the naming here, change it there too.
# -----------------------------------------------------------------------------

if(WIN32)
    set(DEPS_PLATFORM "win_x86_64")
elseif(APPLE)
    # CMAKE_OSX_ARCHITECTURES wins when cross-compiling or building for a
    # single explicit arch; otherwise fall back to the host processor.
    if(CMAKE_OSX_ARCHITECTURES)
        list(GET CMAKE_OSX_ARCHITECTURES 0 _deps_arch)
    else()
        set(_deps_arch "${CMAKE_SYSTEM_PROCESSOR}")
    endif()

    if(_deps_arch STREQUAL "arm64")
        set(DEPS_PLATFORM "macos_arm64")
    else()
        set(DEPS_PLATFORM "macos_x86_64")
    endif()

    unset(_deps_arch)
else()
    set(DEPS_PLATFORM "linux_${CMAKE_SYSTEM_PROCESSOR}")
endif()
