# -----------------------------------------------------------------------------
# stage_hdf5.cmake - collect HDF5 headers and static libraries
# -----------------------------------------------------------------------------
# Run with `cmake -P` from the `stage` target defined in
# recipes/hdf5/CMakeLists.txt. Expects the following variables to be passed
# with -D:
#
#   HDF5_SOURCE_DIR - HDF5 source tree (build/_deps/hdf5-src)
#   HDF5_BUILD_DIR  - HDF5 binary tree (build/_deps/hdf5-build)
#   HDF5_LIB_DIR    - Directory holding the built static libraries
#   OUTPUT_DIR      - Directory to stage into
#   PLATFORM        - Platform suffix, e.g. linux_x86_64 or win_x86_64
#
# Produces:
#   ${OUTPUT_DIR}/include/              - Common HDF5 C/C++ headers
#   ${OUTPUT_DIR}/include_${PLATFORM}/  - Headers generated by the build
#   ${OUTPUT_DIR}/lib_${PLATFORM}/      - Static libraries
# -----------------------------------------------------------------------------

foreach(_required IN ITEMS HDF5_SOURCE_DIR HDF5_BUILD_DIR HDF5_LIB_DIR OUTPUT_DIR PLATFORM)
    if(NOT DEFINED ${_required})
        message(FATAL_ERROR "stage_hdf5.cmake: ${_required} is not set")
    endif()
endforeach()

set(INCLUDE_DIR "${OUTPUT_DIR}/include")
set(GENERATED_INCLUDE_DIR "${OUTPUT_DIR}/include_${PLATFORM}")
set(LIB_DIR "${OUTPUT_DIR}/lib_${PLATFORM}")

file(MAKE_DIRECTORY "${INCLUDE_DIR}" "${GENERATED_INCLUDE_DIR}" "${LIB_DIR}")

# Common headers: C++ API, C API and the subfiling VFD.
file(GLOB HEADERS
    "${HDF5_SOURCE_DIR}/c++/src/*.h"
    "${HDF5_SOURCE_DIR}/src/*.h"
    "${HDF5_SOURCE_DIR}/src/H5FDsubfiling/*.h"
)
if(NOT HEADERS)
    message(FATAL_ERROR "stage_hdf5.cmake: no headers found in ${HDF5_SOURCE_DIR}")
endif()
file(COPY ${HEADERS} DESTINATION "${INCLUDE_DIR}")

# Headers generated by the build, e.g. H5pubconf.h. These are platform
# specific, so they are kept apart from the common headers.
file(GLOB GENERATED_HEADERS "${HDF5_BUILD_DIR}/src/*.h")
if(NOT GENERATED_HEADERS)
    message(FATAL_ERROR "stage_hdf5.cmake: no generated headers found in ${HDF5_BUILD_DIR}/src")
endif()
file(COPY ${GENERATED_HEADERS} DESTINATION "${GENERATED_INCLUDE_DIR}")

# Static libraries.
file(GLOB LIBRARIES
    "${HDF5_LIB_DIR}/*.a"
    "${HDF5_LIB_DIR}/*.lib"
)
if(NOT LIBRARIES)
    message(FATAL_ERROR "stage_hdf5.cmake: no static libraries found in ${HDF5_LIB_DIR}")
endif()
file(COPY ${LIBRARIES} DESTINATION "${LIB_DIR}")

list(LENGTH HEADERS HEADER_COUNT)
list(LENGTH GENERATED_HEADERS GENERATED_HEADER_COUNT)
list(LENGTH LIBRARIES LIBRARY_COUNT)
message(STATUS "Staged ${HEADER_COUNT} headers to ${INCLUDE_DIR}")
message(STATUS "Staged ${GENERATED_HEADER_COUNT} generated headers to ${GENERATED_INCLUDE_DIR}")
message(STATUS "Staged ${LIBRARY_COUNT} libraries to ${LIB_DIR}")
