name: Release on Linux x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        c_compiler: [gcc-11]
        cxx_compiler: [g++-11]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        env:
          CC: ${{matrix.c_compiler}}
          CXX: ${{matrix.cxx_compiler}}
        run: |
          sudo chown -R $USER:$USER /home/runner/work/hdf5-lib-build
          chmod +x build_linux.sh
          ./build_linux.sh
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_linux_x86_64
          path: ./hdf5lib
