name: "Release on MacOS Apple Silicon"

# =============================================================================
# GitHub Actions Workflow: Build and Release HDF5 Static Libraries for MacOS Apple Silicon (arm64)
#
# This workflow builds the HDF5 static libraries and headers using the provided
# build script, and uploads the resulting artifacts for use in downstream jobs or releases.
#
# Triggers:
#   - On push or pull request to the main branch
#
# Artifacts:
#   - hdf5lib_macos_arm64: Contains the built static libraries and headers
# =============================================================================

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Build and Archive HDF5 Libraries"
    runs-on: macos-15
    strategy:
      matrix:
        c_compiler: [clang]
        cxx_compiler: [clang++]

    steps:
      # Checkout repository with submodules
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup Xcode (required for some builds)
      - name: "Setup Xcode"
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.3'

      # (Optional) Cache build dependencies for faster builds
      # - name: "Cache build dependencies"
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/Library/Caches
      #     key: ${{ runner.os }}-hdf5lib-${{ hashFiles('**/CMakeLists.txt') }}

      # Build the project
      - name: "Build HDF5 static libraries and headers"
        env:
          CC: ${{ matrix.c_compiler }}
          CXX: ${{ matrix.cxx_compiler }}
        run: |
          chmod +x build.sh
          ./build.sh

      # Upload the built libraries and headers as an artifact
      - name: "Archive built module"
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_macos_arm64
          path: ./hdf5lib
          retention-days: 14  # Keep artifact for 14 days (default is 90)

      # (Optional) Add a step to verify the contents of the artifact
      # - name: "List artifact contents"
      #   run: |
      #     ls -l ./hdf5lib
