name: Release on Windows x86_64

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          .\build_win.bat
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_win
          path: .\hdf5lib
