name: Release on MacOS Apple Silicon

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        c_compiler: [gcc-13]
        cxx_compiler: [g++-13]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        env:
          CC: ${{matrix.c_compiler}}
          CXX: ${{matrix.cxx_compiler}}
        run: |
          chmod +x build_macos.sh
          ./build_macos.sh
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_macos_arm64
          path: ./hdf5lib
