name: Release on MacOS Apple Silicon

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        c_compiler: [clang]
        cxx_compiler: [clang++]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          # Version of Xcode to use
          xcode-version: '16.3'
      - name: Build
        env:
          CC: ${{matrix.c_compiler}}
          CXX: ${{matrix.cxx_compiler}}
        run: |
          chmod +x build_macos.sh
          ./build_macos.sh
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_macos_arm64
          path: ./hdf5lib
