name: "Release on Windows x86_64"

# =============================================================================
# GitHub Actions Workflow: Build and Release HDF5 Static Libraries for Windows x86_64
#
# This workflow builds the HDF5 static libraries and headers using the provided
# build script, and uploads the resulting artifacts for use in downstream jobs or releases.
#
# Triggers:
#   - On push or pull request to the main branch
#
# Artifacts:
#   - hdf5lib_win_x86_64: Contains the built static libraries and headers
# =============================================================================

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Build and Archive HDF5 Libraries"
    runs-on: windows-latest

    steps:
      # Checkout repository with submodules
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          submodules: true

      # (Optional) Cache build dependencies for faster builds
      # - name: "Cache build dependencies"
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~\AppData\Local\Temp
      #     key: ${{ runner.os }}-hdf5lib-${{ hashFiles('**/CMakeLists.txt') }}

      # Build the project
      - name: "Build HDF5 static libraries and headers"
        run: |
          .\build.bat

      # Upload the built libraries and headers as an artifact
      - name: "Archive built module"
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_win_x86_64
          path: .\hdf5lib
          retention-days: 14  # Keep artifact for 14 days (default is 90)

      # (Optional) Add a step to verify the contents of the artifact
      # - name: "List artifact contents"
      #   run: |
      #     dir .\hdf5lib
