name: Release on MacOS x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        c_compiler: [gcc-14]
        cxx_compiler: [g++-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          # Version of Xcode to use
          xcode-version: '15.2'
      - name: Build
        env:
          CC: ${{matrix.c_compiler}}
          CXX: ${{matrix.cxx_compiler}}
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: hdf5lib_macos_x86_64
          path: ./hdf5lib
